anonymize_params:
  customer_attributes_list:
      - "first_name"
      - "last_name"
      - "address"
      - "date_of_birth"
  anonymize_column_list:
    - "first_name"
    - "last_name"
    - "address"
  record_count: 100
